version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    env_file:
      - .env.test
    depends_on:
      - db
    ports:
      - "3000:3000"
    command:
      - bash
      - -c
      - |
        npx prisma migrate dev --name init
        npm run test:e2e
