# This is a basic workflow to help you get started with Actions

name: Production CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["production"]
  pull_request:
    branches: ["production"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: npm -v

      - name: Set server
        run: npm i

      - run: npm ci

      - name: create env
        run: |
          touch .env

      - name: Set database with ORM
        run: npx prisma migrate dev --init

      - name: build server
        working-directory: ./src/main
        run: |
          npm run start:prod
